---
- name: Enable my.website Nginx site
  hosts: 192.168.0.13
  become: true

  tasks:
    - name: start nginx
      service:
          name: nginx
          state: started
    - name: Create symbolic link for Nginx site
      file:
        src: /etc/nginx/sites-available/my.nginx.com.conf
        dest: /etc/nginx/sites-enabled/my.nginx.com.conf
        state: link
        force: yes
    - name: Restart service httpd, in all cases
      service:
        name: nginx
        state: restarted

